#!/usr/bin/env python3
# ================================================================================================ #
# Project    : Sciven                                                                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.14.3                                                                              #
# Filepath   : /sciven/repos                                                                       #
# Filename   : search.py                                                                           #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.ai                                                            #
# URL        : https://github.com/sciven-centre/sciven                                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Tuesday April 14th 2026                                                             #
# Modified   : Monday June 29th 2026 06:49:26 am                                                   #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2026 John James                                                                 #
# ================================================================================================ #
"""Search repository for the Sciven research pipeline."""

import logging
from typing import Any

from sciven.infra.web_search.base import Search

from sciven.application.discover.curate.arxiv import ArxivSearch
from sciven.domain import EntityType, SourceID, Stage
from sciven.infra.persistence.repo.base import Repo

logger = logging.getLogger(__name__)
# ------------------------------------------------------------------------------------------------ #
#                                   SEARCH API MAPPING                                             #
# ------------------------------------------------------------------------------------------------ #
SOURCEID_MAP: dict[SourceID, type[Search]] = {SourceID.ARXIV: ArxivSearch}

# ================================================================================================ #
#                                REFLECTION REPOSITORY                                             #
# ================================================================================================ #


class SearchRepo(Repo[Search]):
    """Repository for managing Search records.

    Provides methods for creating, retrieving, and searching persisted
    search transactions generated by adapter calls.

    Args:
        adapter: Store adapter for underlying CRUD operations.

    Examples:
        >>> from sciven.adapters.langgraph.store import StoreAdapter
        >>> adapter = StoreAdapter()
        >>> repo = SearchRepo(adapter=adapter)
    """

    # -------------------------------------------------------------------------------------------- #
    def deserialize(self, data: dict) -> Search:
        """Deserializes a value dictionary to a Search instance.

        Args:
            data: Value dictionary containing a ``stage`` field used to
                dispatch to the correct search class.

        Returns:
            A Search instance.
        """
        search_subclass = SOURCEID_MAP.get(SourceID.from_value(data["source_id"]))
        if not search_subclass:  # pragma: no cover - SourceID.from_value already rejects unknowns
            raise ValueError(f"Unsupported SourceID type: {data.get('source_id')}")
        return search_subclass.create(data)

    # -------------------------------------------------------------------------------------------- #
    def deserialize_batch(self, items: list[dict]) -> list[Search]:
        """Deserializes a list of value dictionaries to Search instances.

        Silently skips items that fail deserialization and logs the error.

        Args:
            items: List of value dictionaries to deserialize.

        Returns:
            List of successfully deserialized Search instances.
        """
        searches: list[Search] = []
        for data in items:
            try:
                searches.append(self.deserialize(data))
            except (ValueError, KeyError) as exc:
                logger.warning("Failed to deserialize search: %s", exc)
        return searches

    # -------------------------------------------------------------------------------------------- #
    def summary(self, stage: Stage, limit: int = 1_000_000) -> dict[str, Any]:
        """Summarize searches by source_id within a stage namespace.

        Args:
            stage: Stage used to scope the summary.
            limit: Maximum number of searches to fetch from storage.

        Returns:
            A dictionary containing the total count and per-source_id counts.
        """
        namespace = (stage.value, EntityType.SEARCH.value)
        searches = self.search(namespace, limit=limit)

        total = len(searches)
        if total == 0:
            return {"total": 0, "by_source": {}}

        source_counts: dict[str, int] = {}
        for r in searches:
            source = r.source_id.value if r.source_id else "unknown"
            source_counts[source] = source_counts.get(source, 0) + 1

        return {"total": total, "by_source": source_counts}
